### PR TITLE
Fixed spritesheet animation

### PR DESCRIPTION
**Pull request by gtoast**
https://github.com/molleindustria/p5.play/issues/125

### CODE REVIEW

**Comment by islemaster** [comment]
Thanks for putting together a fix! Taking a look now, as there's a good chance I caused this problem :cry:  For easy access, the currently failing tests are:
```
  2 failing

  1) Sprite dimension updating when animation changes animation width and height get inherited from frame:
     expected NaN to equal 30

  2) Sprite dimension updating when animation changes updates the width and height property when frames are different sizes:
     expected NaN to equal 50
```

**Comment by islemaster** [comment]
Looks like the regression was introduced in https://github.com/molleindustria/p5.play/pull/99 and your fix here re-introduces the bug that _that_ PR was trying to fix.  Let's see if we can fix both.

A unit test to cover this regression would be great too.

**Comment by SnipedCode** [comment]
Is this problem fixed? Cause I can't load my SpriteSheets. please help me

**Comment by islemaster** [comment]
Looking at this today.  Sorry it's been a while!

**Comment by islemaster** [comment]
Replaced by #127, which makes this fix but also has changes to avoid re-introducing the old bug.

**Pull request closed without merging**
