### PR TITLE
Add a unit test suite

### LINKED ISSUE #14: Add a unit test suite
I'd like to add a simple unit test suite in the style of p5's test suite (mocha, phantomJS, Travis CI integration, [nyan cat test formatter](https://github.com/mattsears/nyan-cat-formatter/blob/master/nyan_example.gif), etc). This way future bugs can have regression tests easily written for them.

To start I'd like to just add the test infrastructure along with a regression test for #13.

@molleindustria does this sound okay?

### PR DESCRIPTION
**Pull request by toolness**
This fixes #14 by adding a simple unit test suite with a single regression test for #13.

This PR also configures [Travis](https://travis-ci.org/) to run the tests by adding a `.travis.yml`, but @molleindustria, you will need to explicitly set it up for the repository. Fortunately, the folks at Travis have written up a handy and concise [Travis CI for Complete Beginners](https://docs.travis-ci.com/user/for-beginners) guide!

### CODE REVIEW

**Comment by zachlatta** [comment]
:+1:

**Comment by toolness** [comment]
Woooot thanks!!

**Comment by zachlatta** [comment]
:+1:

Thank you! We're currently using p5.play over in https://gh.hackclub.io and
getting a test suite started makes us feel better about our choice to go
with it.

/cc @jonleung

On Wed, Jan 20, 2016 at 2:26 PM, Atul Varma <notifications@github.com>
wrote:

> Woooot thanks!!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/molleindustria/p5.play/pull/17#issuecomment-173382034>
> .
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by toolness** [comment]
Cool @zachlatta! Let me know if there's any particular parts of the library you'd like to see unit tested.

**Comment by zachlatta** [comment]
Will do! I think @paked or @jonleung will have valuable input on this –
they're much more familiar with our usage of it than I.

On Fri, Jan 22, 2016 at 4:38 AM, Atul Varma <notifications@github.com>
wrote:

> Cool @zachlatta <https://github.com/zachlatta>! Let me know if there's
> any particular parts of the library you'd like to see unit tested.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/molleindustria/p5.play/pull/17#issuecomment-173909786>
> .
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Pull request merged**
