### PR TITLE
Fix: Solver sprite-sheets positioning

### PR DESCRIPTION
**Pull request by GabriMagic**
Related Issues:
- #177 
- #136

### CODE REVIEW

**Comment by GabriMagic** [comment]
I wait to merge this pull request please, in order to use this github as CDN when need to use sprites.

Thanks.

**Comment by hiteq** [comment]
Perfectly works with #136

**Comment by molleindustria** [comment]
I think there was an obscure reason why this was never merged but I don't remember it

**Comment by GabriMagic** [comment]
Thanks for the merge 🙏, I had forgotten about the fix

**Pull request merged**
