### PR TITLE
Fix default camera in instance mode

### PR DESCRIPTION
**Pull request by islemaster**
Attempts to access the lazy-created default `camera` property in instance mode were leading to errors, and it was also interfering with p5's `createGraphics()` [as reported in #104](https://github.com/molleindustria/p5.play/issues/104).  This PR registers an initialization method with p5 [as proposed in #46](https://github.com/molleindustria/p5.play/issues/46) and creates the default camera there instead.  A number of changes were necessary to make this viable, but I think it's worth it, as we can gradually migrate away from lazy-created properties to using the init method for everything.
# p5.js upgrade

I had to upgrade the p5.js version used by the examples; the ability to register an 'init' method was released in [0.4.24](https://github.com/processing/p5.js/releases/tag/0.4.24) and we were on [0.4.21](https://github.com/processing/p5.js/releases/tag/0.4.21).  I went ahead and upgraded all the way to [0.5.4](https://github.com/processing/p5.js/releases/tag/0.5.4).  This means we now depend on p5.js >= 0.4.24, but I'm not sure we've previously recorded that dependency anywhere.  Opinions on where to put it?
# Examples page changes

It seems registering an init method was not working on the examples page because it would load p5.js once on the page, but would eval p5.play with each example - and also because, for some reason, it was clearing all registered methods prior to eval'ing the examples.  I verified that removing this does not cause us to register init too many times.

One nice side effect of this is that you can debug p5.play on the examples page now, which was previously difficult since it was being eval'd.

I think the biggest risk is possible state bleed between examples, but if that's possible I haven't seen it happen yet.  We seem to create a new p5 instance for every example anyway.
# Fix up sprites_with_sheet example

I'm not sure how this was working before - we were using the result of a loadJSON call on another line inside `preload()`, which is not allowed.  To fix, I'm using its result inside a callback - I know it's an advanced technique, but it's probably necessary here if you want to generate a spritesheet in preload() using asynchronously-fetched JSON.

### CODE REVIEW

**Comment by molleindustria** [comment]
I can update the examples on the "official" page if things changed. 
To this date I still have no idea of how instance mode works.

Also, should I set up a github web page that can be updated collectively (right now it's just static stuff on my server)?

**Comment by islemaster** [comment]
Note to self: Although tests are passing, I'd like to clean up the new warning `You just changed the value of "camera", which was a p5 function. This could cause problems later if you're not careful.` before merging.

**Comment by islemaster** [comment]
@molleindustria we are already serving these at [molleindustria.github.io/p5.play](http://molleindustria.github.io/p5.play/), such that anyone with write access to the repository should be able to update it by running [update-gh-pages.sh](https://github.com/molleindustria/p5.play/blob/master/update-gh-pages.sh). [Back in March @toolness suggested](https://github.com/molleindustria/p5.play/issues/57#issuecomment-202535945) a way to have p5play.molleindustria.org point to the version at github.io, using a CNAME DNS record.

It would be a small step now to get that environment to auto-deploy any time `master` is updated - I do exactly that in [this other repo](https://github.com/islemaster/hitotoki) to keep the ["play in browser" feature](http://islemaster.github.io/hitotoki/play.html) current with the master branch.

**Comment by islemaster** [comment]
Regarding the warning, I'm not sure I should fix in this PR; p5.play is legitimately replacing the [p5.js method `camera`](http://p5js.org/reference/#/p5/camera), [present since 0.4.10](https://github.com/processing/p5.js/commit/ac42e37dcc43340c6d56bef1c8feb35c8b4d591e) (September 2015) with its own default camera ([not in the docs but used in the camera.js example](http://p5play.molleindustria.org/examples/index.html?fileName=camera.js)), present at least since the initial commit in June 2015 :frowning_face:.  There just hasn't been a warning until now.

**Comment by islemaster** [comment]
Haven't had a lot of feedback on this change, but it definitely fixes issue so I'm merging.

**Pull request merged**
