### PR TITLE
fixed "Animation" keyword conflict

### PR DESCRIPTION
**Pull request by jeremyglebe**
I renamed the "Animation" class to "SpriteAnimation". All the the examples still seem to run fine. The "camera" conflict is still there, I plan to look at that next, but it only becomes an issue when you are wanting to use the P5.js "camera" function, whereas the "Animation" issue causes p5.play to stop working altogether.

Please accept this pull request or offer feedback on what needs to be changed. I understand this project may not be actively maintained but I would really love to contribute.

### CODE REVIEW

**Comment by molleindustria** [comment]
Hi, sorry for the late answer. Thank you for the add, it's a much requested feature. I suppose the examples would have to be updated as well? I totally forgot how this whole thing works.

Also, should I put the library on some kind of cdn service instead of linking on something under your account?
https://cdn.jsdelivr.net/gh/jeremyglebe/p5.play@master/lib/p5.play.js

I see processing uses cdnjs

**Comment by jeremyglebe** [comment]
As far as I can tell you shouldn't need to update the examples as sprites are usually created via **createSprite** and not through direct instantiation. I haven't dived into the mechanics of the library very much, I was just getting it usable for me and my students.

I used a CDN that led to my repository in the README on my fork of the project but that was just because I wasn't sure if you would see this. Please do get a link for a CDN service.

**Comment by molleindustria** [comment]
Yeah the animations can be created and controlled directly without sprites, they are actually the first three examples:
https://molleindustria.github.io/p5.play/examples/index.html

The logic was meant to mimic p5 Image()

**Comment by jeremyglebe** [comment]
Those appear to use **loadAnimation** and **animation**, which still don't involve any direct instantiation. I am running the examples right now using the changes and I'll verify in a moment if they all appear to be working.

**Comment by jeremyglebe** [comment]
All of the examples appear to be working. As a side note: I'm still as terrible at flappy bird as I remember.

**Comment by molleindustria** [comment]
Alright let's do it. I'm gonna look into the CDN next

**Pull request merged**
